apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx:latest
    command: ["/bin/sh", "-c"]
    args: ["printenv"]
    env:
    - name: CITY
      valueFrom:
        configMapKeyRef:
          name: myconfig
          key: city
    - name: COUNTRY
      valueFrom:
        configMapKeyRef:
          name: myconfig
          key: country
    - name: DBURL
      valueFrom:
        configMapKeyRef:
          name: myconfig
          key: dburl