apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibmtodorest
spec:
  selector:
    matchLabels:
      app: ibmtodorest
  template:
    metadata:
      labels:
        app: ibmtodorest
    spec:
      containers:
      - name: ibmtodorest
        image: shivaspk/ibmtodorest
        ports:
        - containerPort: 9000
        env:
        - name: DBURL
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: dburl
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: USER_NAME
        - name: USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: ibmtodo
spec:
  type: NodePort
  selector:
    app: ibmtodorest
  ports:
  - port: 80
    targetPort: 9000
    nodePort: 31000
